# Generated by Django 3.2.5 on 2022-01-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20220111_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
