# Generated by Django 3.2.5 on 2022-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_alter_scrap_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='csv',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
